services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_DB: clouddb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"